---
- name: Touch file 
  hosts: ansible_clients
  remote_user: ansible
  tasks:
    - name: Create new file
      ansible.builtin.file:
       path: /home/ansible/hello.txt
       owner: ansible
       group: ansible
       mode: 0644
       state: touch

...
